name: RDP
on:
  workflow_dispatch:
    inputs:
      increment:
        type: string
        description: "2fuq66iz69WAgBKrAQaQelMSHCU_85cgojrw9173wRxZxM1Fa"
        required: true
        default: ""
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download Ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip
        Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/download1.jpeg -OutFile wallpaper.bat
        Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/loop.bat -OutFile loop.bat
    - name: Extract ngrok.zip
      run: Expand-Archive ngrok.zip
    - name: Connect Ngrok
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH
      env:
        NGROK_AUTH: ${{ github.event.inputs.increment }}
    - name: Windows 10 RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bat D:\a\wallpaper.bat
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect RDP
      run: cmd /c start.bat
    - name: WIN10 RDP
      run: cmd /c loop.bat